server:
  port: 80

spring:
  application:
    name: cloud-order-service-consul
  cloud:
    consul:
      host: heartzz.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true